language: go
sudo: false
go:
    - 1.8.x
    - 1.9.x
    - tip

before_install:
    # Setup dependency management tool
    - curl -L -s https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -o $GOPATH/bin/dep
    - chmod +x $GOPATH/bin/dep

install:
    - dep ensure
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/megacheck
script:
    - go test -v -race ./...
    - go vet ./...
    - golint -set_exit_status
    - megacheck ./...

