# Note: validate by running
# gem install travis --no-rdoc --no-ri
# travis lint .travis.yml

language: go
sudo: false
go:
  - 1.10.x
  - tip

before_install:
  # Get tools
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

# Thanks to https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139
# for this snippet.
matrix:
  # It's ok if our code fails on unstable development versions of Go.
  allow_failures:
    - go: tip
  # Don't wait for tip tests to finish. Mark the test run green if the
  # tests pass on the stable versions of Go.
  fast_finish: true

script:
  - |
    PATHS="$(gofmt -l -s $(find . -path ./vendor -prune -o -name '*.go' -print))"
    echo "$PATHS" && test "$PATHS" == ""
  - go vet $(go list ./... | grep -v /vendor/)
  - golint -set_exit_status $(go list ./... | grep -v /vendor/)
  - megacheck $(go list ./... | grep -v /vendor/)
  # TODO: After go 1.10 is released, below shell script is unnecessary:
  # "Also, the go test -coverprofile option is now supported when running multiple tests."
  # https://tip.golang.org/doc/go1.10#test
  - |
    echo "mode: atomic" > coverage.txt
    for pkg in $(go list ./... | grep -v /vendor/)
    do
      go test -v -race -coverprofile=tmpcoverage.txt -covermode=atomic $pkg
      tail -n +2 tmpcoverage.txt >> coverage.txt
    done
    rm tmpcoverage.txt
after_success:
  - bash <(curl -s https://codecov.io/bash)
